locale: "en-US"
title: Suman Kumar
subtitle: Linux Kernel Programmer 
description: >- # this means to ignore newlines until "baseurl:"
  An Engineers Logbook

url: "https://sumankumarsp.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: Blog
      url: /blog
    - text: Hire Me
      url: /resume/
    - text: About Me
      url: /about/
    - text: Category
      url : /categories/
    - text: Tag
      url : /tags/
    - text: Contact Me
      url: /contact/
    

# Edit these details 
author_logo: profile.png
author: Suman Kumar
author_bio: >-
  An Embedded Systems engineer with 13 years' extensive hands-on experience writing low-level software for ARM based Qualcomm (APQ) and Freescale (i.MX) chipsets.
author_email: "suman [DOT] read [AT] gmail [DOT] com"
author_location: Palo Alto, California, USA
author_website_url: "https://linkedin.com/in/sumankumarsp"

author_work_experiences: 
            - company_name: CredenceID, LLC
              company_logo: credenceid.png
              company_url: https://credenceid.com
              designation: Systems Engineer
#              description: Worked on various BioMetric Credence ID Products
              visibility: true
            - company_name: Graphene Semiconductors
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Senior Technical Member Staff
#              description: Worked on various Azure Cloud Products
              visibility: true
            - company_name: Inforce Computing Inc.,
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Technical Manager
#              description: Worked on various Azure Cloud Products
              visibility: true
            - company_name: Aricent Communications Inc.,
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Technical Leader
#              description: Worked on various Azure Cloud Products
              visibility: true
            - company_name: Philips
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Software Engineer
#              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: California State University, Eastbay
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Master of Science
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: true

# social links
#twitter_username: sumankumarsp
github_username:  sumankumarsp
#facebook_username: sumankumarsp
linkedin_username: sumankumarsp
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe
stackoverflow_username    : # http://stackoverflow.com/users/123456/username
googlescholar_username    : "http://yourfullgooglescholarurl.com"
researchgate_username     :  # example: "https://www.researchgate.net/profile/yourprofile"
orcid_username            : "http://orcid.org/yourorcidurl"

#for comments using disqus
#disqus_shortname: suman-kumar  

# wakatime username (coding activity)
wakatime_username: sumankumarsp

# formspree (contact form)
formspree_email: suman.read@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

#collections:
#  teaching:
#    output: true
#    permalink: /:collection/:path/
#  publications:
#    output: true
#    permalink: /:collection/:path/
#  portfolio:
#    output: true
#    permalink: /:collection/:path/
#  talks:
#    output: true
#    permalink: /:collection/:path/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
